# Generated by Django 5.1.1 on 2025-07-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordar',
            new_name='order',
        ),
    ]
